### ISSUE TITLE
A possible typo in value

### ISSUE THREAD

**Issue by pombredanne** [seanmacavaney/npids#2]
In the README, the value of 206B storage looks a bit too good to be true!
Could this be a typo?

![Screenshot_2023-10-23 seanmacavaney npids](https://github.com/seanmacavaney/npids/assets/675997/91694586-1f57-43e4-ba98-76bca1f7e6ef)

**Comment by seanmacavaney** [comment]
Actually, it's not too good to be true! 😊

When the package identifies that the IDs are just sequential integers encoded as strings (e.g., `"0"`, `"1"`, `"2"`, ...), it's only a matter of storing some basic metadata about them (prefix, offset, etc.) to facilitate string <-> index conversions.

For instance, the conversions for the MS MARCO passage IDs are just `str(idx)` and `int(id)`. No need to store any of the identifiers or indices.

This is actually one of the motivating use cases for this package. It felt really silly to have files that map sequential integers like this.

**Comment by seanmacavaney** [comment]
@pombredanne does this resolve your issue?

**Comment by pombredanne** [comment]
Clear. Thanks!
